# -*- coding: utf-8 -*-
"""QR midterm project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YcwIMGfv_Le_d6rp9oTvmKDJQ9EIeoLx

IMPORT LIB AND FILES
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import seaborn as sb
import scipy.stats

data_url = "https://raw.githubusercontent.com/Lilvutra/Quantitative-Reasoning-Spring-2023/main/landoceantemp.csv"
data_url2 = "https://raw.githubusercontent.com/Lilvutra/Quantitative-Reasoning-Spring-2023/main/1_CO2-data.csv"
globaltempanomaly = pd.read_csv(data_url, sep = ';')
Co2level = pd.read_csv(data_url2, sep = ',')

globaltempanomaly.head()

"""DESCRIPTIVE STATISTICS

1. Global temperature anomaly
"""

x=globaltempanomaly['Year'] 
y=globaltempanomaly['Lowess(5)']

plt.axhline(y=0, color="y")

plt.text(1890, 0.2, "1951-1980 average", color="darkorange") 

plt.xlabel("Year")
plt.ylabel("Temperature anomalies")

plt.title("Global Average Temperature Anomaly")

plt.plot(globaltempanomaly["Year"], globaltempanomaly["Lowess(5)"], color = "palevioletred")

sns.scatterplot(x, y, color = "darkorange")

plt.figure()
plt.style.use("fivethirtyeight")
plt.plot(x,y, color = "darkorange")
plt.title("Annual anomaly from base mean temperature (Global)")
plt.xlabel('Year')
plt.ylabel('Temperature Anomaly')
plt.show()

"""We can infer from the graph that the temperature is on the rise """

tempconcat2 = pd.concat([globaltempanomaly["No_Smoothing"], globaltempanomaly["Lowess(5)"]])

tempconcat2

keke2 = tempconcat2.dropna()

keke2.hist(bins = 10, edgecolor = "white", color = "cadetblue")
plt.title("Average Temperature Anomaly Histogram")
plt.xlabel("Range")
plt.ylabel("Frequency")

plt.figure(figsize=(10,6))
plt.boxplot(keke2, vert = False)
plt.title("Land Average Temperature Anomaly Boxplot")
plt.show()

"""2. Global CO2 level"""

Co2level.head()

x2=Co2level['year']
y2=Co2level['trend']

sns.scatterplot(x2, y2, color = "palevioletred")

plt.figure()
plt.style.use("fivethirtyeight")
plt.plot(x2,y2, color = "palevioletred")
plt.title("Global CO2 level trend")
plt.xlabel('Year')
plt.ylabel('CO2 level')
plt.show()

"""CO2 level is on a steady rise since 1960

"""

sb.scatterplot(y2, y, color = "palevioletred")
plt.title('Temperature anomalies and CO2 trend')
plt.ylabel('Temperature anomalies')
plt.xlabel('CO2 level')
plt.show()

"""We can observe that temperature anomalies have a positive correlation with CO2 level in the recent period """

period = Co2level[(Co2level["year"] >= 1958) & (Co2level["year"] <= 2017)]

period

period2 = globaltempanomaly[(globaltempanomaly["Year"] >= 1958) & (globaltempanomaly["Year"] <= 2017)]

df = pd.read_csv("https://raw.githubusercontent.com/Lilvutra/Quantitative-Reasoning-Spring-2023/main/1_CO2-data.csv")
Co2level["year"] = pd.to_datetime(df['year'])
mean_df = df.groupby('year').mean()

print(mean_df)

mean_df.reset_index().head()

period2.head()

x3=period2['Lowess(5)']
y3=mean_df['trend']

np.corrcoef(x3, y3)

"""The Pearson coefficient returned is 0.99185732, therefore, ***the temperature anomalies and the CO2 level*** are positively correlated.

3. Sea level
"""

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/Lilvutra/Quantitative-Reasoning-Spring-2023/main/sealevel.csv")

year = []
year_average = []
for nam in range(1993, 2022):
  df_nam = df[df['Year'] == nam]['GMSL_noGIA'];
  year_average.append(df_nam.mean());
  year.append(nam);
 
import matplotlib.pyplot as plt

plt.style.use("fivethirtyeight")
plt.plot(year, year_average, color = 'palevioletred')
plt.title("Global Sea level Variations")
plt.ylabel('Sea level')
plt.xlabel('Year')

"""Global sea level is on a steady rise since 1993"""

df = pd.read_csv("https://raw.githubusercontent.com/Lilvutra/Quantitative-Reasoning-Spring-2023/main/sealevel.csv")

 df['Year'] = pd.to_datetime(df['Year'])

 mean_sealevel = df.groupby('Year').mean()

print(mean_sealevel)

meansealevel2 = mean_sealevel.reset_index()

meansealevel2

x4=meansealevel2['GMSL_noGIA']

period3 = globaltempanomaly[(globaltempanomaly["Year"] >= 1993) & (globaltempanomaly["Year"] <= 2021)]

period3.head()

xglobaltemp1993= period3['Lowess(5)']

xglobaltemp1993

xglobaltemp1993

x4

from matplotlib import rcParams
rcParams['figure.figsize'] = 8,6
plt.axvline(0, c=(.5, .5, .5),ls='--')
plt.axhline(0)
plt.title("Global Sea level Variations and Temperature anomalies scatterplot")
plt.ylabel('Sea level variations')
plt.xlabel('Temperature anomalies')
plt.scatter(xglobaltemp1993,x4, color = 'palevioletred');

np.corrcoef(xglobaltemp1993, x4)

"""r = 0.9147479 shows that ***global temperature is positively correlated with sea level***"""